### ISSUE TITLE
Agregar data property plazasPorTurno

### ISSUE THREAD

**Issue by ednaru** [CiudadesAbiertas/vocab-sector-publico-empleo#5]
Agregar data property plazasPorTurno el cual está especificado en el diseño conceptual y ejemplos. Se refiere al número de plazas (entero) por cada Turno.

**Comment by flowsta** [comment]
Resulta que en el diagrama, la documentación y los ejemplos está la dp plazasxturno pero cuando @jcballesteros @hlafuente estaban con la API advertieron que la nomenclatura debiera ser "plazasPorTurno".

Añadida a la ontología https://github.com/CiudadesAbiertas/vocab-sector-publico-empleo/commit/1b02a440d45722949c64f87ef549e3ecbf7f42bd, a empleo.owl, pero falta generar nueva documentación y cambiar ejemplos

**Comment by flowsta** [comment]
Generada nueva documentación con repaso de ejemplos e imágenes en commits https://github.com/CiudadesAbiertas/vocab-sector-publico-empleo/commit/71fd8167e887eb738988c5b483b7ce9c4aaa20b1 y https://github.com/CiudadesAbiertas/vocab-sector-publico-empleo/commit/08829caef8db832f5b0cf5cc8c8c599f690a7e47

**Comment by flowsta** [comment]
Seguía sin aparecer plazasPorTurno por doquier :desert:  https://github.com/CiudadesAbiertas/vocab-sector-publico-empleo/commit/4561643677cd02bb998c9852b06660fb0156703a Corregido :palm_tree: @ednaru
